import thumbnail from '../../assets/images/thumbnail.png';

export default class MovieService {

  getMovieList() {
    return Promise.resolve([
      {
        id:1,
        title: 'Action Movie',
        genre: 'Action1',
        movieUrl: 'http://imdb.com/1',
        overView: 'overView',
        rating: 4.5,
        runTime: 90,
        releasedDate: '2002-12-02',
        thumbnail,
      },{
        id:2,
        title: 'Action Movie',
        genre: 'Action2',
        movieUrl: 'http://imdb.com/1',
        overView: 'overView',
        rating: 4.5,
        runTime: 90,
        releasedDate: '2002-12-02',
        thumbnail,
      },{
        id:3,
        title: 'Action Movie',
        genre: 'Action3',
        movieUrl: 'http://imdb.com/1',
        overView: 'overView',
        rating: 4.5,
        runTime: 90,
        releasedDate: '2002-12-02',
        thumbnail,
      },{
        id:4,
        title: 'Action Movie',
        genre: 'Action4',
        movieUrl: 'http://imdb.com/1',
        overView: 'overView',
        runTime: 90,
        rating: 4.5,
        releasedDate: '2002-12-02',
        thumbnail,
      },{
        id:5,
        title: 'Action Movie',
        genre: 'Action5',
        movieUrl: 'http://imdb.com/1',
        overView: 'overView',
        runTime: 90,
        rating: 4.5,
        releasedDate: '2002-12-02',
        thumbnail,
      },{
        id:6,
        title: 'Action Movie',
        genre: 'Action',
        movieUrl: 'http://imdb.com/1',
        overView: 'overView',
        runTime: 90,
        rating: 4.5,
        releasedDate: '2002-12-02',
        thumbnail,
      },{
        id:7,
        title: 'Action Movie',
        genre: 'Action',
        movieUrl: 'http://imdb.com/1',
        overView: 'overView',
        runTime: 90,
        rating: 4.5,
        releasedDate: '2002-12-02',
        thumbnail,
      },{
        id:8,
        title: 'Action Movie',
        genre: 'Action',
        movieUrl: 'http://imdb.com/1',
        overView: 'overView',
        runTime: 90,
        rating: 4.5,
        releasedDate: '2002-12-02',
        thumbnail,
      },{
        id:9,
        title: 'Action Movie',
        genre: 'Action',
        movieUrl: 'http://imdb.com/1',
        overView: 'overView',
        runTime: 90,
        rating: 4.5,
        releasedDate: '2002-12-02',
        thumbnail,
      },
    ])
  }
}